```toml
[advisory]
id = "RUSTSEC-2020-0074"
package = "pyo3"
aliases = ["CVE-2020-35917"]
cvss = "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H"
date = "2020-11-28"
url = "https://github.com/PyO3/pyo3/pull/1297"
keywords = ["memory-corruption"]

[versions]
patched = [">= 0.12.4"]
unaffected = ["< 0.12.0"]
```

# Reference counting error in `From<Py<T>>`

A bug in `From<Py<T>>` would lead to an extra reference count decrement, often
leading to use-after-free issues.
